name: unlock-protocol
recipe: wordpress
config:
  via: nginx
  php: 7.4
  webroot: wordpress
  database: mariadb
  xdebug: true
services:
  appserver:
    overrides:
      volumes:
        - ".lando.wp-cli.yml:/wp-cli.yml"
        - ".:/app/wordpress/wp-content/plugins/unlock-protocol"
        - "/app/wordpress/wp-content/plugins/unlock-protocol/wordpress"
    build_as_root:
      - apt update -y && apt install -y apt-transport-https
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs zip
    build:
      - wp core download --force --skip-content --path=/app/wordpress
      - cd assets && npm ci
    run:
      - wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --skip-check --force
      - sleep 2 # For some reason, we have to wait at least two seconds till database is up.
      - wp core install --url=https://$LANDO_APP_NAME.$LANDO_DOMAIN --title=$LANDO_APP_NAME --admin_user=admin --admin_email=admin@example.com --admin_password=admin
      - wp theme install --activate twentytwenty
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
tooling:
  npm:
    service: appserver
  node:
    service: appserver
events:
  pre-start:
    - cd assets && npm install --no-save
